//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reciept
    {
        public int RecieptId { get; set; }
        public int TransactionId { get; set; }
    }
}
