//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionId { get; set; }
        public System.DateTime Date { get; set; }
        public int AmountofTransaction { get; set; }
        public int AccountId { get; set; }
        public int TransactionTypeId { get; set; }
        public int AccountingSubjectId { get; set; }
        public string OtherDetails { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AccountingSubject AccountingSubject { get; set; }
        public virtual TransactionType TransactionType { get; set; }
    }
}
